-- V3__create_chat_messages_table.sql
-- Create chat_messages table expected by MessageEntity

CREATE TABLE IF NOT EXISTS public.chat_messages (
                                                    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                    room_id    VARCHAR(255)      NOT NULL,
    sender     VARCHAR(255)      NOT NULL,
    content    VARCHAR(4000)     NOT NULL,
    created_at TIMESTAMPTZ       NOT NULL DEFAULT now()
    );

-- Existing index you already had from JPA annotation (safe to create if missing)
CREATE INDEX IF NOT EXISTS idx_chat_messages_room_created
    ON public.chat_messages (room_id, created_at);

-- Keyset/cursor pagination helper index (newest-first, stable tie-break by id)
CREATE INDEX IF NOT EXISTS idx_chat_messages_room_created_id_desc
    ON public.chat_messages (room_id, created_at DESC, id DESC);
